services:
  dev:
    image: python-lab
    container_name: python-lab-dev

    build:
      context: .
      dockerfile: docker/Dockerfile

    volumes:
      - .:/workspace

    tty: true
    stdin_open: true

    command: bash

  web:
    image: python-lab
    container_name: python-lab-web
    working_dir: /workspace
    build:
      context: .
      dockerfile: docker/Dockerfile

    volumes:
      - .:/workspace

    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/workspace/src
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8000